dist: xenial
language: node_js
node_js:
  - "12"
  - "10"
  - "8"
  - "6"
script:
  - npm run test:standard
  - npm run test:node
  - xvfb-run --auto-servernum npm run test:browser
  - xvfb-run --auto-servernum npm run test:transform-browser
  - xvfb-run --auto-servernum npm run test:babel-browser
services:
  - xvfb
